# Generated by Django 5.0 on 2025-01-15 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('Total_items', models.IntegerField()),
                ('Total_spent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Category', models.CharField(choices=[('Vegetables', 'Vegetables'), ('Junk', 'Junk')], max_length=10)),
                ('Platform', models.CharField(blank=True, choices=[('Zepto', 'Zepto'), ('Blinkit', 'Blinkit'), ('Instamart', 'Instamart')], default='Zepto', max_length=10)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.date')),
            ],
        ),
    ]
