# Generated by Django 5.0 on 2025-01-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_date_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='Total_spent',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='items',
            name='Price',
            field=models.FloatField(),
        ),
    ]
